package pojos;
// Generated 30 nov 2023 22:23:52 by Hibernate Tools 4.3.1

/**
 * Equipo generated by hbm2java
 */
public class Equipo extends Torneo implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int titulares;
     private int suplentes;
     private String directorTecnico;
     private int puntos;
     private int partidosJugados;

    public Equipo() {
    }

    public Equipo(String nombre, int titulares, int suplentes, String directorTecnico) {
       this.nombre = nombre;
       this.titulares = titulares;
       this.suplentes = suplentes;
       this.directorTecnico = directorTecnico;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getTitulares() {
        return this.titulares;
    }
    
    public void setTitulares(int titulares) {
        this.titulares = titulares;
    }
    public int getSuplentes() {
        return this.suplentes;
    }
    
    public void setSuplentes(int suplentes) {
        this.suplentes = suplentes;
    }
    public String getDirectorTecnico() {
        return this.directorTecnico;
    }
    
    public void setDirectorTecnico(String directorTecnico) {
        this.directorTecnico = directorTecnico;
    }
    public int getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(int puntos) {
        this.puntos += puntos;
    }
    public int getPartidosJugados() {
        return this.partidosJugados;
    }
    
    public void setPartidosJugados(int partidosJugados) {
        this.partidosJugados += partidosJugados;
    }

    


}


